[toolchain]
channel = "nightly-2024-02-24" #TODO: this crate nshould be relatively easy to work only on stable
components = [ "rustfmt", "clippy", "rust-src" ]
targets = [ "riscv32imc-unknown-none-elf" ]
profile = "minimal"
